services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Monte le dossier actuel dans le conteneur
      - /app/node_modules # Évite les conflits avec node_modules de l'hôte
    environment:
      NODE_ENV: development
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_PORT: 5432
      AUTH_SECRET: 5DUYX6WPQiSB8gj/MRLWnoiTVRGHkL8s22gmSLgadLE=

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: thomas.lacroix4@etu.unilim.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db-data: